### ISSUE TITLE
Program crashes instead of displaying error in GUI.

### ISSUE THREAD

**Issue by joerivstrien** [joerivstrien/process_maxquant#5]
When running the tool on a dataset with gi numbers instead of uniprot ID's, but leaving the option   "uniprot_step" on, the tool and GUI shut down/crash instead of the error being displayed in the GUI.

Traceback: 
`Traceback (most recent call last):
  File "/home/joeri/Documents/coding_projects/process_maxquant/gui_file_acceptor.py", line 149, in execute_process_maxquant_script
    protein_groups_dataframe = fetch_uniprot_annotation_step(self, protein_groups_dataframe, settings_dict)
  File "/home/joeri/Documents/coding_projects/process_maxquant/process_maxquant.py", line 948, in fetch_uniprot_annotation_step
    protein_data_dict = fetch_uniprot_annotation(gui_object, protein_groups_dataframe["identifier"], settings_dict["uniprot_step"])
  File "/home/joeri/Documents/coding_projects/process_maxquant/process_maxquant.py", line 305, in fetch_uniprot_annotation
    request.raise_for_status()
  File "/home/joeri/miniconda3/envs/py3new/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.ebi.ac.uk/proteins/api/proteins?offset=0&size=100&accession=10048432,...110625963,110625975,110625979
Aborted (core dumped)
`

**Comment by ArielKomen** [comment]
Whenever the uniprot query returned a bad request the program automatically shut down to display the HTTP error. When transforming the code for the GUI I forgot that this needed to be changed. I have made sure that this bug doesn't occur anymore.
Anyway, uniprot can do little with GI identifiers which results in that each column from uniprot has NA values and each mitocarta column also has NA values. It would be good to make it clear to the user that UNIPROT identifiers are needed and not something else!
